import type { Metadata } from "next";
import "./styles/globals.css";
import { QueryProvider } from "./client/components/QueryProvider";
import { JotaiProvider } from "./client/JotaiProvider";
export const metadata: Metadata = {
  title: "ハローワーク求人情報検索",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <JotaiProvider>
          <QueryProvider>{children}</QueryProvider>
        </JotaiProvider>
      </body>
    </html>
  );
}
