import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "ハローワーク求人情報検索",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>{children}</body>
    </html>
  );
}
