import type { Metadata } from "next";
import "./styles/globals.css";
import { Provider } from "jotai";
export const metadata: Metadata = {
  title: "ハローワーク求人情報検索",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
